spring:
  application:
    name: entrance
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: your_user
    password: your_password
  jpa:
    hibernate:
      ddl-auto: update

